# Generated by Django 5.0.3 on 2024-03-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='videos',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
